### ISSUE TITLE
Add to Composer

### ISSUE THREAD

**Issue by SmoshySmosh** [csev/tsugi#19]
It would be really nice to see a TSUGI implementation (as a utility) added to composer (https://getcomposer.org/) for easy implementation into projects.

**Comment by csev** [comment]
I am working on this - parts of the code have been move to Composer.   I need to move more.

**Comment by csev** [comment]
While I don't have any releases per se, I have a tsugi project in composer:

https://packagist.org/packages/tsugi/lib

You can pull it in as follows:

https://github.com/csev/tsugi/blob/master/composer.json

Let me know if/when we need to do releases - I just keep moving the code forward.

**Comment by SmoshySmosh** [comment]
@csev It would be very useful to do releases so people using the code do not unintentionally upgrade to newer revisions of the unversioned code that may not work the same as the revision they were on previously.
